### ISSUE TITLE
Grafik verileri

### ISSUE THREAD

**Issue by enverarslan** [prosman/dovizcom-api#2]
Grafik çizdirmek için zaman aralıklı veriler [Sadece satış fiyatı ve zaman verisi içerir.]

Günlük USD: 
http://doviz.com/api/v1/currencies/USD/daily
Haftalık, Aylık, Yıllık gibi diğer zaman aralıkları için:
http://doviz.com/api/v1/currencies/USD/archive?start=2015-01-01&end=2016-01-01

Bu deseni altın ve borsa için de kullanabilirsiniz.

Örnekler: 
http://www.doviz.com/api/v1/golds/gram-altin/daily
http://doviz.com/api/v1/golds/gram-altin/archive?start=2015-01-01&end=2016-01-01
http://www.doviz.com/api/v1/stocks/ACSEL/daily
http://www.doviz.com/api/v1/stocks/ACSEL/archive?start=2015-01-01&end=2016-01-01

**Comment by prosman** [comment]
Bilgilendirme için teşekkürler, hemen ekliyorum :)
