### ISSUE TITLE
timestamp formatı

### ISSUE THREAD

**Issue by ardakaplan** [prosman/dovizcom-api#3]
Selam,

gelen cevapta;

[{"selling":3.8123,"update_date":1520715598,"currency":1,"buying":3.8101,"change_rate":-0.26162258326138,"name":"amerikan-dolari","full_name":"Amerikan Dolar\u0131","code":"USD"},

Sun Jan 18 1970 14:25:15 tarihini gösteriyor

update_date alanı date e dönüşünce yanlış bilgi geliyor. Bunun üstesinden nasıl gelebiliriz ?

**Comment by ajansnaber** [comment]
gelen cevap unix timestamp olarak geliyor.

moment.js ile basit bir şekilde:

var dateString = moment.unix(1520715598).format("DD/MM/YYYY");

şeklinde normal tarih formatına çevirebilirsin.

[https://momentjs.com/docs/](url)

**Comment by prosman** [comment]
Moment.js ile örneği: 
`var now = moment.unix(1520870488).format('DD.MM.YYYY HH:mm');`
`alert(now);`
PHP ile örneği: 
`date_default_timezone_set('Europe/Istanbul');`
`echo date('d.m.Y H:i:s',1520870488);`

**Comment by ardakaplan** [comment]
Unix zaman formatını bilmiyordum. İsmi yetti =) teşekkürler
