### ISSUE TITLE
Cors Hatası

### ISSUE THREAD

**Issue by safacaki** [prosman/dovizcom-api#5]
Apiler react axios'ta cors hatası veriyor. Nasıl çözebiliriz?

**Comment by prosman** [comment]
@safacaki React konusunda hakim değilim fakat https://github.com/shalvah/cors-escape ile çözüm bulanlar varmış araştırdığımda. Bu da olmaz ise klasik yöntem Cors a takılmadan PHP ile cURL kullanarak kendi sunucundan çektirebilirsin.

**Comment by safacaki** [comment]
@prosman  denicem

**Comment by enesguven09** [comment]
Axios yerine es6 fetch kullanılırsa cors sorunu ortadan kalkıyor.

**Comment by MuhammedBalta** [comment]
Fetch de işe yaramıyor. Yine cors hatası veriyor.    
fetch('http://www.doviz.com/api/v1/indexes/all/latest' , {
        mode:'no-cors', //Mode 'no-cors' da hata almıyor ama veride yazdırmıyor. 
        method:'GET' 
    })
        .then(response => response.json())
        .then(json => console.log(json))

**Comment by aakyel** [comment]
Aynı durum bende de var

**Comment by prosman** [comment]
Daha önceden de belirtmiştim direkt asla çekmemeye çalışın. Cache tutarak kendi sunucunuzda dataları tutmayı çalışın. Aksi taktirde direkt JS v.b. yollarda sıkıntı çıkartabiliyor.
