### ISSUE TITLE
Açık Kod?

### ISSUE THREAD

**Issue by MuhammedBalta** [prosman/dovizcom-api#6]
Öncelikle ellerine sağlık güzel bir api yapmışsın. Bu kodlarını burada niye paylaşmıyorsun bizde eklemeler yapalım.

**Comment by prosman** [comment]
> Öncelikle ellerine sağlık güzel bir api yapmışsın. Bu kodlarını burada niye paylaşmıyorsun bizde eklemeler yapalım.

Merhaba, paylaşılacak bir kod yok. Sadece API servisi. Dileyen istediği yazaılım dilini kullarak bu API yi kullanabilir.

**Comment by bigboytr** [comment]
Ben küçük bir uygulama yazdım. Web app olarak. Bir süre sonra doviz.com tarafından domain im banlandı. Şuan istek atamıyorum. Fazla sayıda istek atıldığında banlıyorlar domaini, kullanacakların aklında olsun
