### ISSUE TITLE
Grafik Parametreleri

### ISSUE THREAD

**Issue by muhammedakiftas** [prosman/dovizcom-api#7]
Grafikleri gün, hafta, ay, yıl, 10 yıl olarak nasıl çekebiliriz ?

**Comment by prosman** [comment]
Merhaba, veriler arşivden günlük olarak geliyor son 1 hafta, son 1 yıl gibi kendiniz çekip grafiğe aktarabilirsiniz. Ayrıca gelen verilerden kendiniz haftalık aylık gibi arşiv verisini kullanarak bölümlendirebilirsiniz. Doviz.com kendi sitesinde de "BUGÜN - 365" veya "BUGÜN - 7" şeklinde grafiklendirmiş.

https://doviz.com/api/v2/currencies/USD/archive?start=2017-01-01&end=2018-01-01
https://doviz.com/api/v2/currencies/USD/archive?start=2018-02-01&end=2018-01-01
