### ISSUE TITLE
BIST verilerine ulaşılamıyor

### ISSUE THREAD

**Issue by Ckatalay** [prosman/dovizcom-api#8]
BIST verisini alamıyorum metadata çıktısı veriyor
Edit: Şu an itibariyle dolar euro ve pound’da da ulaşılamıyor

**Comment by msyagli** [comment]
Aynen, 404 veriyor.

**Comment by prosman** [comment]
> Aynen, 404 veriyor.
> BIST verisini alamıyorum metadata çıktısı veriyor

Merhaba kendi mobil uygulalarında da **Hisse** verileri çıkmıyor.

**Comment by atak946** [comment]
Merhaba,
çözümlenir mi aceba veya başka bir çözüm mü baksak ?

**Comment by aakyel** [comment]
doviz.com sanırım api'leri kapattı şu an hiç biri çalışmıyor

**Comment by prosman** [comment]
> doviz.com sanırım api'leri kapattı şu an hiç biri çalışmıyor

Şuan sadece **Hisse** verileri gelmiyor, diğerleri çalışıyor. Doviz.com un mobil uygulamalarında da **HİSSE** bölümü çalışmıyor.

**Comment by aakyel** [comment]
![screen shot 2018-11-06 at 16 37 47](https://user-images.githubusercontent.com/14162549/48067979-a9a7b900-e1e2-11e8-809a-977dba31b3a7.png)

**Comment by prosman** [comment]
Merhaba tekrar, doviz.com sistemi güncellemiş sanırım. Yeni bir yol bulmaya çalışıyorum.

**Comment by aakyel** [comment]
> Merhaba tekrar, doviz.com sistemi güncellemiş sanırım. Yeni bir yol bulmaya çalışıyorum.

Emekleriniz için teşekkürler

**Comment by prosman** [comment]
Merhaba herkese tekrardan...

Şimdilik yeni bir repository açtım alternatif kanallar için https://github.com/prosman/doviz-borsa-kripto-api

**Comment by prosman** [comment]
Merhaba herkese en son durum User-Agent ile yeni güncellemelerinin üstesinden gelinmiştir, Readme dosyasından kontrolünü sağlayabilirsiniz. https://github.com/prosman/dovizcom-api
