### ISSUE TITLE
403 Aauthorization 

### ISSUE THREAD

**Issue by ongun23** [prosman/dovizcom-api#9]
Bu sabah itibariyle bütün API adresleri 403 Aauthorization hatası veriyor.

**Comment by Ecancan** [comment]
Doviz.com tarafindan dis isteklere kapatildi yeni apiler.

**Comment by mcuneyda** [comment]
ücretli ücretsiz alternatif bir kaynak var mı? bende bekliyorum.

**Comment by avnibu** [comment]
> Eski apiler aktif suan sadece.

ben v1 kullaniyordum. ona da erisim engellenmis. Hangisi bu bahsettiginiz eski apiler?

**Comment by CanOzp** [comment]
Arkadaşlar önereceğiniz bir kaynak var mı? Eski api de geçmişi çekemiyorum.

**Comment by prosman** [comment]
Merhaba herkese tekrardan...

Şimdilik yeni bir repository açtım alternatif kanallar için https://github.com/prosman/doviz-borsa-kripto-api

**Comment by aliosmanyuksel** [comment]
Herkese merhabalar.

Doviz.com API sorunu için çözüm üretmiş bulunmaktayım. Porjeyi fork ederek kendi tarafımda güncelle başlığı altında açıkladım.

https://github.com/aliosmanyuksel/dovizcom-api

İyi çalışmalar.

**Comment by prosman** [comment]
> Herkese merhabalar.
> 
> Doviz.com API sorunu için çözüm üretmiş bulunmaktayım. Projeyi fork ederek kendi tarafımda güncelle başlığı altında açıkladım.
> 
> https://github.com/aliosmanyuksel/dovizcom-api
> 
> İyi çalışmalar.

Teşekkürler Ali Osman, bunu orjinale ekliyorum.

**Comment by aliosmanyuksel** [comment]
@prosman ben teşekkür ederim.

### PHP (cURL)

```

# Doviz.com API için PHP Örneği

$url = 'https://www.doviz.com/api/v5/currencies/all/latest';
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_TIMEOUT, 5);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_USERAGENT, 'Doviz/5.2.0 (com.nokta.Finans-Takip; build:1; iOS 12.1.0) Alamofire/4.7.3');
curl_setopt($ch,CURLOPT_ENCODING, 'gzip;q=1.0, compress;q=0.5');
$data = curl_exec($ch);
curl_close($ch);
echo $data;

```

Anlamayanlar açısından ufak bir örnek olması için ekliyorum.
